var articles = ["The Alt-Truth: A Serious Miscalculation and the Repercussions that Followed", "Voting in the United States Explained", "Crisis in South Sudan"/*, "Pirating Music is Fun"*/];
var writers = ["Alex Serbanescu", "Caroline Magoc", "Oliver Frank and Debi Saha"/*, "James Madison"*/];
var text = [];
var prevtext = [];
var vol = [1, 1, 1];
var iss = [1, 1, 1];
var art = [0, 1, 2];
var img = ["http://www.billboard.com/files/styles/article_main_image/public/media/donald-trump-thumbs-up-aug-2015-billboard-650.jpg", "http://www.usnews.com/dims4/USNEWS/5c287b1/2147483647/thumbnail/970x647/quality/85/?url=%2Fcmsmedia%2Ffb%2Fa0c6e9a1c7db237875eb9a9af49192%2Fresizes%2F1500%2Fmedia%3A95bb2d0fba214be08616d61b25fcc7a0Obama.JPEG", "http://media.salon.com/2014/04/karl_marx.jpg", "https://static01.nyt.com/images/2016/11/11/us/politics/donald-trump-administration-1478905372015/donald-trump-administration-1478905372015-videoSixteenByNineJumbo1600-v2.jpg"];
text[0] = ''+
'On January 21, 2017, the establishment was universally shocked (following what seems to be a strong trend since 2016). Liberals and the mainstream media were offended and succumbed to the lowest form of mockery and dismissal. It was this day when counselor to the 45th President of the United States, Kellyanne Conway, used the term “alternative facts” when discussing President Trump’s inaugural crowd size. Esteemed journalist Dan Rather issued a scathing criticism (ironically on a Facebook post) saying “Facts and the truth are not partisan. They are the bedrock of our democracy. And you are either with them, with us, with our Constitution, our history, and the future of our nation, or you are against it. Everyone must answer that question.” To me, this statement proves why the establishment lost the 2016 election and, barring any radical event, will lose the 2020 election.'+
'<br>&emsp;&emsp;&emsp;'+
'In my previous article, “Alien: How Radical Extremists Hijacked My Party, and Why They Must Be Stopped,” I detailed the rise of “anti-intellectualism, a cancer on the conservative movement.” This article is a retraction of that statement. What I viewed as stupidity, what the establishment derisively calls “Orwellian newspeak,” is actually a set of legitimate concerns many Americans have had for decades. Together, I call their narrative the “alt-truth.” And if we in the establishment dismiss and ignore this narrative, it will come back and bite us harder than ever before.'+
'<br>&emsp;&emsp;&emsp;'+
'What I and many in the establishment viewed as ignorance was actually belief in a different reality, one that is more skeptical and cynical, one that was living in the shadows for years. Conspiracy theorist Alex Jones is a radical example of this movement. While many have dismissed him as irrelevant, I believe we need to take a hard look at his narrative and analyze it fully. He believes that there is a culture war, intended to destroy the family unit as the cornerstone of society and replace it with the state, in an attempt to control more people. He believes that the weapons used to wage this war on the American people are organizations such as the EPA and Child Protective Services, laws that erode freedom such as gun control, narratives (propaganda) that indoctrinate the young in the form of pop culture, and chemical warfare in the form of vaccines, GMOs, and fluoride in drinking water. With the exception of the last weapon (which was practically stolen from a Stanley Kubrick film), the alt-truthers believe in many of the same things. They are inherently skeptical of change and being told that change is good.'+
'<br>&emsp;&emsp;&emsp;'+
'Us big-city “intellectuals” cannot wrap our minds around the idea of fearing your own government. We see those who have power over us in a benevolent light, regardless of whether we agree with their politics of not. That is because we have benefited from the system. We are relatively comfortable in our surrounding, and we have no idea of the struggles that Trump voters face. Meryl Streep displayed this brazen ignorance in front of an audience of millions in her speech during the Golden Globes. To an echo chamber filled with Hollywood glitterati, she outwardly dismissed the alt-truth, even going to the point where she lectured them on what was true entertainment and what wasn’t. Regardless of whether you agree with my analysis of her speech or not, it must be understood that the alt-truthers agree with me. They might not outwardly express their outrage, but it furthers their narrative of an “us against them” world.'+
'<br>&emsp;&emsp;&emsp;'+
'So how do we defeat the alt-truth? How do we convince the people that we deserve to be listened to? To be perfectly honest, I have no idea. Clearly, starting a national conversation on this issue wouldn’t hurt, but how can you do that if we are so incredibly filtered in discussions? We would need to suspend the rules of political correctness and expose the inner feelings of the alt-truthers. Think of it as mass psychoanalysis (Freud would be so proud). But who’s to say, if we actually find the root of the problem, that we would want to fix it? Perhaps it would involve giving up some of our control. Regardless, what I can definitively say is that we were wrong in labeling this movement as one of stupidity.'+
'<br>&emsp;&emsp;&emsp;'+
'To close off this article, I will use a literary example, just as Dan Rather did in his criticism. Liberals refer to this administration as Orwellian, so I will call the establishment reminiscent of Aldous Huxley’s Brave New World. Alt-truthers had an allergic reaction to what they saw as indoctrination. They saw the government trying to separate them into castes, remove the idea of “mother” and “father,” normalize impure and sinful behavior, all for the purposes of oppression. See, it isn’t hard to understand the mindset of the alt-truth movement, you could just read Huxley. But we have to disassociate ourselves from our inherent biases. And fast.'

text[1] = ''+
'A few months ago, millions of Americans were shocked when they woke up on November 9th to find that Donald Trump would be their next president. A few hours later, they had come to the stinging realization that although Hillary Clinton had defeated Trump in the popular vote (by millions, I might add), the electoral college had deemed Trump the president-elect. It sounds unfair, but the ground rules for the 2016 presidential election have been set for centuries. In fact, out of all elections in which the electoral college has played a par, four have elected the person who did not get the popular vote. So, how does this happen?'+
'<br>&emsp;&emsp;&emsp;'+
'The first flaw of the electoral college is that it rewards more electoral votes per person to less populated states than to more populated states. This is done to increase attention given to people living in the states with low populations. During the campaigning process, candidates focus their efforts on swaying the voters in swing states like Ohio and Colorado, again leaving large states the short end of the stick. Political minorities in large states (Republicans in New York, Democrats in Texas) are left out in the Winner-Take-All elections that make up the electoral college, and are usually also disregarded by the candidates they care about.'+
'<br>&emsp;&emsp;&emsp;'+
'Another large flaw of the electoral college is that the electors, who supposedly cast their votes in accordance with the views of their state, can completely disregard the decision of the state’s citizens. There are 538 electors, and, assuming they each represented an equal amount of voters in the 2016 election (which is not necessarily true), each elector would represent over 258,000 voting citizens. In the 2016 election, there were seven “faithless” electors who switched their votes. Regardless of who they switched to, this theoretically means that over 1,800,000 votes lost meaning through the actions of seven people.'+
'<br>&emsp;&emsp;&emsp;'+
'Now that we’ve discussed the problem, what’s the solution? While many believe that the solution lies in directly amending the Constitution, the National Popular Vote Bill works by fighting to be passed in multiple states. When enacted, the bill works by guaranteeing that the state in question gives all of its electoral votes to the candidate who wins the National Popular Vote (NPV). This bill has already been enacted in ten states, but said states have always been overwhelmingly democratic, and thus did not impact the recent election. If this bill passes in enough states to make up 270 electoral votes, it ensures a victory for the candidates who win the NPV, ensuring that the people do indeed elect their leader.'+
'<br>&emsp;&emsp;&emsp;'+
'Few are involved in the process of getting the NPV Bill passed, but all are witness to the weirdly shaped assembly districts, congressional districts, and state senate districts. Looking at state senate districts, my mom pointed out one running all the way from Greenpoint to Woodhaven and said that it looked like a T-Rex. Sadly, going to maps.nyc.gov reveals too many of these gerrymanders. Gerrymandering is a way to limit the voices of some and to amplify the voices of others. For those unfamiliar with the process of gerrymandering, gerrymandering (named after Elbridge Gerry) achieves its goal by manipulating the boundaries of an electoral constituency. Politicians manipulate these boundaries when district lines are redrawn every ten years, as per the U.S. Census results. Following the 2010 Census, organizations like REDMAP 2010 (redistricting majority project) raised millions of dollars to help Republican campaigns for state legislature, or assemblies. The state legislature, a group of partisan politicians, is the main decider of district lines in many states. Naturally, this idea is flawed.'+
'<br>&emsp;&emsp;&emsp;'+
'Given a scenario where Republicans take hold of the state legislature in a swing state, they can redraw district lines in such a way that Democratic voters are packed into a single district, while the remaining Democratic voters are spread in with Republican voters.  In this way, the say of Democrats are minimized and maximized are the say of Republicans, as all districts have an equal say. In real-life scenarios, we see this in the form of minorities being sectioned into single districts, and weirdly shaped districts as a result. Following the redrawing of district lines in 2011, 2012 U.S. House Elections in North Carolina suffered greatly from gerrymandering. While Democrat candidates for the House of Representatives won 51% of the vote from the citizens in total, decisive gerrymandering meant that they only won 31% of U.S. House seats. Overall, the 2012 U.S. House Elections were the first in forty years where the party that received the most votes did not control the House.'+
'<br>&emsp;&emsp;&emsp;'+
'With REDMAP 2020 kicking off over a year ago, it is clear that gerrymandering is a priority of the Republican Party. When gerrymandering is involved, incumbents are favored and a candidate can take office even if they are disliked. Movements to better the situation include YouDrawTheLines2021, which works to establish non-partisan redistricting efforts. This is better than bipartisan redistricting efforts, which work to keep elected officials in office. Multiple states have programs that fight gerrymandering. Some states force district lines to be approved on by a supermajority (2/3rds of the vote in each house) in the state legislature, but this again encourages bipartisan redistricting. Other states make sure that both the senate and the house of the state agree on the lines (joint resolution), while others yet have advisory commissions which advise the state legislature on where to draw their lines, as well as congressional lines. Finally, some states have backup commissions, which work to redraw lines if the legislature does not pass a plan.'+
'<br>&emsp;&emsp;&emsp;'+
'Knowing the many ways government officials can silence a citizen’s voice is crucial to spurring change, and as such anyone can decide what they think of our many voting systems, and whether or not they enforce equality. Statistics don’t lie, but different interpretations of them lead to many varied ideas for how the United States should change their voting system in the many decades to come. While some propose enforcing the current electoral college to emphasize the votes of small states, others believe that the electoral college should be scrapped, and that another voting system should be implemented altogether (STV, Alternative Vote, etc.). The same applies for issues closer to home, such as gerrymandering, that help decide the politicians we contact if we have any problems.'+
'<br>&emsp;&emsp;&emsp;'+
'Regardless of how we choose to counter the many problems in our voting systems as a country, we must fight with a moral obligation to make sure our voices are heard, perhaps not always in the form of protests, but by ensuring that what we write on the ballot means something.'


text[2] = ''+
'From the 1950s onwards, Sudan has been constantly plagued by war. With a Muslim majority northern region and a traditional and Christian south, ethnic tensions have been incredibly high in the past few decades. Prior to gaining its independence in 2011, South Sudanese cultures were unified in the many conflicts between 1955 and 2011 against the northern government that had left them hungry, impoverished, and broken. Many believed that the end to the civil war would see an end to violence in Sudan; however, the truce between cultures quickly broke apart and descended into chaos after South Sudan gained its independence. The two main factions who took over after independence was gained were the Dinka and the Nuer tribes. At first, the Dinka and the Nuer joined as a coalition government, in order to signify peace between the two longstanding rivals, but as previously mentioned, this relationship has simply degraded into another civil war. More than 50,000 casualties later, along with mass rapes, and ethnic cleansings, there has still been little foreign intervention into an affair oddly reminiscent to the Rwandan genocide. As well as that, news coverage of the topic has been limited.<br>&emsp;&emsp;&emsp;'+
	'As Americans, with basic respect for human dignancy, it is our obligation to help these people in anyway we can. Under Obama’s presidency, our country failed the people of South Sudan, and especially the children of South Sudan. In opposition to the Child Soldiers Prevention Act (CSPA), which aims to sanction countries which use child soldiers, the Obama administration provided upwards of $99 million to the Sudan People’s Liberty Army (SPLA), along with various other rebel groups which has been identified as using child soldiers. This clear violation of the CSPA shows our government\'s utter neglect of the issue, in exchange for a paycheck. However, despite the White House’s complacency on the issue, they at the very least addressed it quite a few times. However, under Mr. Trump’s new administration, the issue has never been so much as mentioned, and it is unclear whether Mr. Trump is even aware of the issue.<br>&emsp;&emsp;&emsp;'+
	'While many issues have remained inadequately addressed or simply unaddressed by the Trump administration, this is certainly one of the most important, although it is not one talked about often. While issues such as abortion or LGBT rights in America seem the most pressing to us, the fact that helpless children are having guns pushed into their hands, and told to face certain death for their country is frankly inexcusable. What’s more is that our government actively provides funding to the militias who operate in South Sudan. After the Rwandan genocide of 1994, the U.S. and other powers vowed to never let something like that happen again. However, as the death toll mounts, and only the UN peacekeepers are there the protect innocent civilians and children, one must ask the question; when is the rest of the world going to intervene? It is our job as the privileged to help the needy. Donations to humanitarian efforts in the area (such as Oxfam) or writing letters to your congressmen are excellent ways to help out in South Sudan. No amount of effort is too little, and every penny matters. There is a lot that needs to be done, and it starts with you.'

/*
text[3] = ''+
'Trysail chantey starboard Jack Ketch warp belay Admiral of the Black landlubber or just lubber spyglass Gold Road. Plate Fleet rutters keel line scourge of the seven seas measured fer yer chains spanker snow hempen halter doubloon. Yawl plunder rigging schooner Pieces of Eight topsail avast long boat Sail ho red ensign.<br>&emsp;&emsp;&emsp;'+
'Ho overhaul spike keelhaul long clothes belaying pin grog blossom jury mast draft barque. Killick booty square-rigged smartly topgallant pillage dead men tell no tales keelhaul yawl haul wind. Jack ballast Nelsons folly marooned holystone trysail aye interloper Brethren of the Coast Plate Fleet.<br>&emsp;&emsp;&emsp;'+
'Scourge of the seven seas reef sails gally me hornswaggle rutters furl keel bounty bowsprit. Driver flogging sutler main sheet salmagundi overhaul prow Jolly Roger bilged on her anchor doubloon. List chase scourge of the seven seas crack Jennys tea cup pressgang parley heave down case shot dance the hempen jig dead men tell no tales.<br>&emsp;&emsp;&emsp;'
*/

for (var i = 0; i < text.length; i++) {
	//prevtext[i] = text[i].substr(0, 500) + "...";
	//prevtext[i] = text[i].get(0).firstChild.data;
	prevtext[i] = text[i].split("<br>")[0] + "<a href='Vol1Iss1Art"+ i + ".html'> <b>(Read More)</b></a>";
}
