var articles = ["Lorem Ipsum Dolor Sit Amet", "Star Trek Themed Lorem", "Cupcakes Taste Good", "Pirating Music is Fun"];
var writers = ["George Washington", "John Adams", "Thomas Jefferson", "James Madison"];
var text = [];
var vol = [2, 2, 1, 1];
var iss = [1, 1, 2, 1];
var img = ["http://www.billboard.com/files/styles/article_main_image/public/media/donald-trump-thumbs-up-aug-2015-billboard-650.jpg", "http://www.usnews.com/dims4/USNEWS/5c287b1/2147483647/thumbnail/970x647/quality/85/?url=%2Fcmsmedia%2Ffb%2Fa0c6e9a1c7db237875eb9a9af49192%2Fresizes%2F1500%2Fmedia%3A95bb2d0fba214be08616d61b25fcc7a0Obama.JPEG", "http://media.salon.com/2014/04/karl_marx.jpg", "https://static01.nyt.com/images/2016/11/11/us/politics/donald-trump-administration-1478905372015/donald-trump-administration-1478905372015-videoSixteenByNineJumbo1600-v2.jpg"];
text[0] = ''+
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque velit dui, ullamcorper ut odio sed, porta varius ante. Fusce ornare convallis sagittis. Donec dapibus, tellus nec eleifend porta, magna odio luctus purus, non eleifend odio dui ut leo. Phasellus lacinia lorem eu arcu fringilla pulvinar. Vestibulum tincidunt ac nibh placerat tempus. Integer condimentum felis nibh, et volutpat lorem viverra at. Morbi hendrerit vehicula mi a aliquet. Nulla lectus ante, dictum vel commodo at, consectetur at justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam volutpat laoreet dui, posuere accumsan tellus fringilla eget. Vestibulum non porttitor felis. Nullam nec gravida dui. Cras nec turpis metus. Donec turpis purus, consectetur at nibh iaculis, commodo dignissim nibh.'+
'<br>'+
'Quisque rutrum gravida pharetra. Praesent sem turpis, dictum vel risus vel, ultricies ultricies nisl. Maecenas vulputate faucibus leo vitae convallis. Sed sed neque ut eros dictum maximus. In libero nibh, euismod et vestibulum id, mollis quis nisi. Praesent lacinia arcu ligula, id accumsan dolor accumsan eu. Duis lacinia ornare neque, vitae sagittis nisi porttitor ut. Sed feugiat porttitor pharetra. Vivamus iaculis, urna at venenatis vehicula, nibh leo consequat risus, vel semper justo velit sed ex.'+
'<br>'+
'In porta interdum porttitor. Nam sollicitudin nulla in est dictum accumsan id quis ligula. Cras vitae faucibus velit, et blandit mauris. Donec eget elementum nisi. Duis aliquam nisi orci, interdum imperdiet ex consectetur eget. Nunc dignissim odio magna, pretium bibendum ipsum malesuada ac. Nunc pretium lorem odio, et aliquet dui maximus eu. Quisque eu rutrum magna, quis tempor nisl. Sed finibus velit sit amet turpis lobortis convallis. Proin ut egestas nisi. Pellentesque a consectetur risus. Phasellus ut libero lectus. Sed sed dignissim turpis.'+
'<br>'+
'Nullam eu commodo risus. Vestibulum viverra nisl magna, vitae rutrum sem tincidunt id. Sed venenatis est vel felis vehicula, et egestas lectus rutrum. Etiam in massa eu diam dictum tempus. Fusce bibendum elit vitae rhoncus consequat. Quisque dapibus arcu quis arcu consequat blandit. Suspendisse porta velit lacus, eget gravida ante scelerisque eu. Nam eu elit at velit pharetra finibus sit amet porttitor velit. Etiam vitae est risus. Etiam feugiat feugiat dolor vel facilisis. Quisque ut dui eu neque iaculis consequat quis quis nunc. Cras porttitor felis diam, id ultrices purus volutpat at. Vestibulum tristique nisi id consequat rutrum. Quisque quis erat dui. Fusce aliquam lorem in lorem suscipit egestas eget nec lectus.'+
'<br>'+
'Sed pulvinar libero eros, at finibus neque pretium a. Fusce id mi quis mauris interdum commodo vel id lorem. Sed fermentum sed orci et tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec varius velit odio, sed scelerisque tellus gravida at. Fusce placerat lorem nec pharetra eleifend. Donec mollis, nisl a vestibulum condimentum, ligula nunc fermentum libero, ut molestie nibh mi sit amet ante. Suspendisse mollis maximus luctus.'

text[1] = ''+
'These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. We need to neutralize the homing signal. Each unit has total environmental control, gravity, temperature, atmosphere, light, in a protective field. Sensors show energy readings in your area. We had a forced chamber explosion in the resonator coil. Field strength has increased by 3,000 percent.'+
'<br>'+
'Deflector power at maximum. Energy discharge in six seconds. Warp reactor core primary coolant failure. Fluctuate phaser resonance frequencies. Resistance is futile. Recommend we adjust shield harmonics to the upper EM band when proceeding. These appear to be some kind of power-wave-guide conduits which allow them to work collectively as they perform ship functions. Increase deflector modulation to upper frequency band.'+
'<br>'+
'Exceeding reaction chamber thermal limit. We have begun power-supply calibration. Force fields have been established on all turbo lifts and crawlways. Computer, run a level-two diagnostic on warp-drive systems. Antimatter containment positive. Warp drive within normal parameters. I read an ion trail characteristic of a freighter escape pod. The bomb had a molecular-decay detonator. Detecting some unusual fluctuations in subspace frequencies.'+
'<br>'+
'Now what are the possibilities of warp drive? Cmdr Riker\'s nervous system has been invaded by an unknown microorganism. The organisms fuse to the nerve, intertwining at the molecular level. That\'s why the transporter\'s biofilters couldn\'t extract it. The vertex waves show a K-complex corresponding to an REM state. The engineering section\'s critical. Destruction is imminent. Their robes contain ultritium, highly explosive, virtually undetectable by your transporter.'+
'<br>'+
'Unidentified vessel travelling at sub warp speed, bearing 235.7. Fluctuations in energy readings from it, Captain. All transporters off. A strange set-up, but I\'d say the graviton generator is depolarized. The dark colourings of the scrapes are the leavings of natural rubber, a type of non-conductive sole used by researchers experimenting with electricity. The molecules must have been partly de-phased by the anyon beam.'

text[2] = ''+
'Cupcake ipsum dolor sit. Amet biscuit jelly-o. Jelly-o sesame snaps dessert ice cream bonbon brownie. Sesame snaps dessert chupa chups cake croissant biscuit. Tart gummi bears carrot cake marshmallow sweet roll tootsie roll sweet carrot cake. Pie apple pie topping candy pastry biscuit. Wafer danish fruitcake halvah gummi bears tiramisu cupcake marshmallow. Muffin icing ice cream icing lollipop.<br>'+
'Soufflé muffin bonbon candy canes soufflé jujubes toffee marzipan. Chocolate bar carrot cake jelly-o marzipan cupcake chupa chups. Tart cake candy. Cheesecake jelly-o biscuit jelly beans. Soufflé halvah marzipan jelly dessert lemon drops danish. Cake brownie caramels cheesecake. Pastry cake ice cream tiramisu jujubes dessert. Gummi bears tart jelly-o sweet jelly-o danish icing.<br>'+
'Jujubes cheesecake tart wafer jelly chocolate cake cookie. Apple pie marshmallow gummies ice cream toffee bonbon sesame snaps donut. Croissant tootsie roll powder brownie jelly beans chocolate bar marzipan. Halvah tootsie roll ice cream dragée chocolate cake cupcake brownie. Wafer powder fruitcake lollipop fruitcake. Marzipan pastry cake cupcake topping pastry soufflé. Sesame snaps topping jelly beans powder biscuit. Cotton candy ice cream tiramisu muffin dessert topping. Lemon drops sweet roll halvah cotton candy marzipan powder biscuit pudding gummies.<br>'+
'Oat cake pastry bonbon marshmallow tiramisu gummies chupa chups powder. Cotton candy icing powder macaroon fruitcake cupcake icing topping jujubes. Muffin halvah toffee cookie. Macaroon bear claw bonbon danish tiramisu jelly-o powder ice cream. Biscuit cupcake jelly-o. Sweet cake candy canes chocolate cake.<br>'+
'Fruitcake chocolate cake muffin jelly. Gingerbread bonbon topping. Gummi bears biscuit liquorice cookie bear claw jelly gummi bears. Chocolate caramels cheesecake. Wafer gingerbread sweet. Macaroon oat cake gummies lollipop apple pie jelly-o marshmallow sesame snaps toffee.'

text[3] = ''+
'Trysail chantey starboard Jack Ketch warp belay Admiral of the Black landlubber or just lubber spyglass Gold Road. Plate Fleet rutters keel line scourge of the seven seas measured fer yer chains spanker snow hempen halter doubloon. Yawl plunder rigging schooner Pieces of Eight topsail avast long boat Sail ho red ensign.<br>'+
'Ho overhaul spike keelhaul long clothes belaying pin grog blossom jury mast draft barque. Killick booty square-rigged smartly topgallant pillage dead men tell no tales keelhaul yawl haul wind. Jack ballast Nelsons folly marooned holystone trysail aye interloper Brethren of the Coast Plate Fleet.<br>'+
'Scourge of the seven seas reef sails gally me hornswaggle rutters furl keel bounty bowsprit. Driver flogging sutler main sheet salmagundi overhaul prow Jolly Roger bilged on her anchor doubloon. List chase scourge of the seven seas crack Jennys tea cup pressgang parley heave down case shot dance the hempen jig dead men tell no tales.<br>'
